"""
schemas.py
----------
Pydantic models for request validation and response serialisation.

FastAPI uses these to:
- Validate incoming request bodies (wrong types → automatic 422 error)
- Serialise outgoing responses to JSON
- Generate the Swagger UI documentation automatically
"""

from typing import Optional
from pydantic import BaseModel, Field


# ── Request models ─────────────────────────────────────────────────────────────

class QueryFilters(BaseModel):
    """
    Optional pre-filters applied before semantic search.
    Any field left as None is simply not applied.
    """
    patient_sex: Optional[str] = Field(
        default=None,
        description="Filter by patient sex. Accepted values: 'Male', 'Female'",
        examples=["Male", "Female"]
    )
    patient_age_group: Optional[str] = Field(
        default=None,
        description=(
            "Filter by age group. "
            "Accepted values: 'infant', 'child', 'adolescent', "
            "'young_adult', 'middle_aged', 'elderly'"
        ),
        examples=["middle_aged", "adolescent"]
    )

    def to_dict(self) -> dict:
        """
        Return only the fields that are actually set (not None).
        This is what gets passed to the retriever.
        """
        return {k: v for k, v in self.model_dump().items() if v is not None}


class QueryRequest(BaseModel):
    """
    Incoming request body for POST /query.
    """
    patient_query: str = Field(
        ...,
        description="Plain English patient complaint or symptom description",
        min_length=5,
        max_length=1000,
        examples=["I have been having severe knee pain for two weeks, worse when walking"]
    )
    filters: Optional[QueryFilters] = Field(
        default=None,
        description="Optional filters to narrow retrieval by patient demographics"
    )
    top_k: int = Field(
        default=5,
        ge=1,
        le=10,
        description="Number of cases to retrieve. Between 1 and 10."
    )


# ── Response models ────────────────────────────────────────────────────────────

class RetrievedCase(BaseModel):
    """Metadata for a single retrieved clinical case."""
    idx: str = Field(description="Case identifier from the dataset")
    score: float = Field(description="Similarity score between 0 and 1")
    patient_sex: Optional[str] = Field(default=None)
    patient_age_group: Optional[str] = Field(default=None)
    patient_age: Optional[int] = Field(default=None)
    primary_diagnosis: Optional[str] = Field(default=None)
    visit_motivation: Optional[str] = Field(default=None)


class QueryResponse(BaseModel):
    """
    Response body for POST /query.
    """
    answer: str = Field(
        description="Grounded clinical response generated by the LLM"
    )
    cases_used: int = Field(
        description="Number of clinical cases passed to the LLM as context"
    )
    cases: list[RetrievedCase] = Field(
        description="Metadata for each retrieved case"
    )
    query: str = Field(
        description="Original query echoed back"
    )
    model: str = Field(
        description="LLM model used for generation"
    )
    retrieval_ms: int = Field(
        description="Time taken for retrieval in milliseconds"
    )
    generation_ms: int = Field(
        description="Time taken for LLM generation in milliseconds"
    )
    total_ms: int = Field(
        description="Total pipeline time in milliseconds"
    )


# ── Health check response ──────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    status: str = Field(description="Service status", examples=["ok"])
    qdrant: str = Field(description="Qdrant connection status", examples=["ok", "error"])
    document_store: str = Field(description="Document store status", examples=["ok", "error"])
    model: str = Field(description="Embedding model name")